const ar = [
    {
        name: "K437突击步枪",
        basic_damage: 34,
        benifit_shootrange: 40,
        recoil: 45,
        scope_open_speed: 55,
        holding_stability: 53,
        hipfire_accuracy: 49,
        armor_damage: 35,
        shoot_speed: 780,
        capacity: 30,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 757,
        noise_broadcast_distance: 500,
        ammo_type: ".300 BLK",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "左导轨",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "上导轨",
            "侧瞄具"
        ],
        type: "步枪",
    },
    {
        name: "M7战斗步枪",
        basic_damage: 38,
        benifit_shootrange: 50,
        recoil: 34,
        scope_open_speed: 55,
        holding_stability: 58,
        hipfire_accuracy: 47,
        armor_damage: 40,
        shoot_speed: 649,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 630,
        noise_broadcast_distance: 600,
        ammo_type: "6.8 x 51mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "导轨脚架",
            "上导轨",
            "左导轨",
            "右导轨",
            "左贴片",
            "右贴片",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
        ],
        type: "步枪",
    },
    {
        name: "ASh-12战斗步枪",
        basic_damage: 56,
        benifit_shootrange: 55,
        recoil: 24,
        scope_open_speed: 52,
        holding_stability: 61,
        hipfire_accuracy: 43,
        armor_damage: 55,
        shoot_speed: 500,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 340,
        noise_broadcast_distance: 600,
        ammo_type: "12.7 x 55mm",
        supported_components: [
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "弹匣",
            "瞄准镜",
            "上导轨",
            "左导轨",
            "右导轨",
            "侧瞄具",
        ],
        type: "步枪",
    },
    {
        name: "K416突击步枪",
        basic_damage: 31,
        benifit_shootrange: 27,
        recoil: 44,
        scope_open_speed: 61,
        holding_stability: 52,
        hipfire_accuracy: 57,
        armor_damage: 35,
        shoot_speed: 880,
        capacity: 30,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.56 x 45mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "上导轨",
            "左导轨",
            "右导轨",
            "上贴片",
            "左贴片",
            "右贴片",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "枪托套件"
        ],
        type: "步枪",
    },
    {
        name: "AS Val突击步枪",
        basic_damage: 29,
        benifit_shootrange: 27,
        recoil: 43,
        scope_open_speed: 62,
        holding_stability: 51,
        hipfire_accuracy: 57,
        armor_damage: 48,
        shoot_speed: 972,
        capacity: 15,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 330,
        noise_broadcast_distance: 100,
        ammo_type: "9 x 39mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪托",
            "弹匣",
            "瞄准镜",
            "前握把",
            "左导轨",
            "右导轨",
            "侧瞄具",
            "拉机柄"
        ],
        type: "步枪",
    },
    {
        name: "M4A1突击步枪",
        basic_damage: 29,
        benifit_shootrange: 40,
        recoil: 41,
        scope_open_speed: 58,
        holding_stability: 55,
        hipfire_accuracy: 55,
        armor_damage: 32,
        shoot_speed: 800,
        capacity: 30,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.56 x 45mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "导轨脚架",
            "上导轨",
            "左导轨",
            "右导轨",
            "上贴片",
            "左贴片",
            "右贴片",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "枪托套件"
        ],
        type: "步枪",
    },
    {
        name: "AUG突击步枪",
        basic_damage: 32,
        benifit_shootrange: 55,
        recoil: 60,
        scope_open_speed: 54,
        holding_stability: 59,
        hipfire_accuracy: 53,
        armor_damage: 35,
        shoot_speed: 679,
        capacity: 30,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.56 x 45mm",
        supported_components: [
            "枪管",
            "枪管",
            "枪托",
            "前握把",
            "瞄准镜",
            "右导轨",
            "侧瞄具",
            "弹匣",
            "弹匣座",
            "托腮板"
        ],
        type: "步枪",
    },
    {
        name: "AK-12突击步枪",
        basic_damage: 29,
        benifit_shootrange: 40,
        recoil: 48,
        scope_open_speed: 57,
        holding_stability: 56,
        hipfire_accuracy: 54,
        armor_damage: 41,
        shoot_speed: 735,
        capacity: 30,
        fire_mode: "全自动/单发/连发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.45 x 39mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "上导轨",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "拉机柄"
        ],
        type: "步枪",
    },
    {
        name: "SC步枪-H战斗步枪",
        basic_damage: 40,
        benifit_shootrange: 40,
        recoil: 40,
        scope_open_speed: 58,
        holding_stability: 55,
        hipfire_accuracy: 45,
        armor_damage: 40,
        shoot_speed: 585,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 630,
        noise_broadcast_distance: 600,
        ammo_type: "7.62 x 51mm",
        supported_components: [
            "枪口",
            "枪托",
            "前握把",
            "瞄准镜",
            "右导轨",
            "侧瞄具",
            "弹匣",
            "弹匣座",
            "后握把"
        ],
        type: "步枪",
    },
    {
        name: "AKM突击步枪",
        basic_damage: 40,
        benifit_shootrange: 40,
        recoil: 40,
        scope_open_speed: 58,
        holding_stability: 55,
        hipfire_accuracy: 45,
        armor_damage: 40,
        shoot_speed: 585,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 630,
        noise_broadcast_distance: 600,
        ammo_type: "7.62 x 51mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "枪托垫",
            "前握把",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "拉机柄"
        ],
        type: "步枪",
    },
    {
        name: "腾龙突击步枪",
        basic_damage: 35,
        benifit_shootrange: 27,
        recoil: 40,
        scope_open_speed: 60,
        holding_stability: 50,
        hipfire_accuracy: 56,
        armor_damage: 38,
        shoot_speed: 706,
        capacity: 30,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.8x42mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "导气系统",
            "枪托",
            "前握把",
            "上导轨",
            "左导轨",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "枪托垫"
        ],
        type: "步枪",
    },
    {
        name: "SG552突击步枪",
        basic_damage: 24,
        benifit_shootrange: 35,
        recoil: 46,
        scope_open_speed: 61,
        holding_stability: 52,
        hipfire_accuracy: 53,
        armor_damage: 31,
        shoot_speed: 906,
        capacity: 20,
        fire_mode: "单发/全自动/连发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.56x45mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具"
        ],
        type: "步枪",
    },
    {
        name: "G3战斗步枪",
        basic_damage: 39,
        benifit_shootrange: 55,
        recoil: 32,
        scope_open_speed: 51,
        holding_stability: 62,
        hipfire_accuracy: 45,
        armor_damage: 42,
        shoot_speed: 533,
        capacity: 20,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 630,
        noise_broadcast_distance: 600,
        ammo_type: "7.62×51mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "导轨脚架",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具"
        ],
        type: "步枪",
    },
    {
        name: "QBZ95-1突击步枪",
        basic_damage: 28,
        benifit_shootrange: 55,
        recoil: 52,
        scope_open_speed: 55,
        holding_stability: 58,
        hipfire_accuracy: 54,
        armor_damage: 42,
        shoot_speed: 679,
        capacity: 30,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.8x42mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "弹匣",
            "弹匣座",
            "前握把",
            "托腮板",
            "护木套件"
        ],
        type: "步枪",
    },
    {
        name: "PTR-32突击步枪",
        basic_damage: 34,
        benifit_shootrange: 40,
        recoil: 32,
        scope_open_speed: 56,
        holding_stability: 57,
        hipfire_accuracy: 45,
        armor_damage: 36,
        shoot_speed: 632,
        capacity: 30,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 630,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x39mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具"
        ],
        type: "步枪",
    },
    {
        name: "C步枪-15突击步枪",
        basic_damage: 27,
        benifit_shootrange: 40,
        recoil: 50,
        scope_open_speed: 58,
        holding_stability: 55,
        hipfire_accuracy: 53,
        armor_damage: 32,
        shoot_speed: 632,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.56x45mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "下导轨",
            "右导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "枪托套件"
        ],
        type: "步枪",
    },
    {
        name: "M16A4突击步枪",
        basic_damage: 33,
        benifit_shootrange: 55,
        recoil: 40,
        scope_open_speed: 56,
        holding_stability: 57,
        hipfire_accuracy: 54,
        armor_damage: 39,
        shoot_speed: 672,
        capacity: 20,
        fire_mode: "单发/连发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 500,
        ammo_type: "5.56x45mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "下导轨",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "枪托套件"
        ],
        type: "步枪",
    },
    {
        name: "AKS-74U突击步枪",
        basic_damage: 34,
        benifit_shootrange: 40,
        recoil: 35,
        scope_open_speed: 60,
        holding_stability: 53,
        hipfire_accuracy: 52,
        armor_damage: 36,
        shoot_speed: 533,
        capacity: 20,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 500,
        ammo_type: "5.45x39mm",
        supported_components: [
            "后握把",
            "枪口",
            "枪托",
            "枪托垫",
            "护木",
            "前握把",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "上护木",
            "拉机柄"
        ],
        type: "步枪",
    },
    {
        name: "Vector冲锋枪",
        basic_damage: 32,
        benifit_shootrange: 20,
        recoil: 38,
        scope_open_speed: 69,
        holding_stability: 42,
        hipfire_accuracy: 52,
        armor_damage: 28,
        shoot_speed: 1091,
        capacity: 17,
        fire_mode: "全自动/单发/连发",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 300,
        ammo_type: ".45 ACP",
        supported_components: [
            "枪管",
            "枪口",       // 修正OCR"检口"
            "枪托",
            "弹匣",
            "弹匣座",
            "前握把",
            "瞄准镜",
            "上导轨",
            "侧瞄具"     // 修正OCR"初瞄具"
        ]
    }
]