const machinegun = [
    {
        name: "PKM通用机枪",
        basic_damage: 45,
        benifit_shootrange: 40,
        recoil: 36,
        scope_open_speed: 42,
        holding_stability: 59,
        hipfire_accuracy: 45,
        armor_damage: 42,
        shoot_speed: 669,
        capacity: 75,
        fire_mode: "全自动",
        muzzle_base_speed: 630,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x54mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "瞄准镜",
            "弹匣",
            "枪托",
            "后握把"
        ],
        type: "轻机枪",
        weight: 6.8,
        size: 10
    },
    {
        name: "M249轻机枪",
        basic_damage: 30,
        benifit_shootrange: 40,
        recoil: 44,
        scope_open_speed: 47,
        holding_stability: 55,
        hipfire_accuracy: 48,
        armor_damage: 38,
        shoot_speed: 858,
        capacity: 100,
        fire_mode: "全自动",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 600,
        ammo_type: "5.56x45mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "左导轨",
            "右导轨",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托",
        ],
        type: "轻机枪",
        weight: 6.5,
        size: 12
    },
    {
        name: "M250通用机枪",
        basic_damage: 55,
        benifit_shootrange: 40,
        recoil: 45,
        scope_open_speed: 38,
        holding_stability: 50,
        hipfire_accuracy: 55,
        armor_damage: 53,
        shoot_speed: 550,
        capacity: 125,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 600,
        noise_broadcast_distance: 600,
        ammo_type: "6.8x51mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "左导轨",
            "右导轨",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托",
        ],
        type: "轻机枪",
        weight: 6.8,
        size: 12
    }
]