const marksman = [
    {
        name: "Mini-14射手步枪",
        basic_damage: 32,
        benifit_shootrange: 90,
        recoil: 60,
        scope_open_speed: 52,
        holding_stability: 63,
        hipfire_accuracy: 37,
        armor_damage: 38,
        shoot_speed: 590,
        capacity: 10,
        fire_mode: "单发",
        muzzle_base_speed: 650,
        noise_broadcast_distance: 600,
        ammo_type: "5.56x45mm",
        supported_components: [
            "枪口",
            "枪管",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "弹匣"
        ],
        type: "射手步枪",
        weight: 4.19,
        size: 10
    },
    {
        name: "VSS射手步枪",
        basic_damage: 35,
        benifit_shootrange: 120,
        recoil: 46,
        scope_open_speed: 54,
        holding_stability: 61,
        hipfire_accuracy: 38,
        armor_damage: 48,
        shoot_speed: 480,
        capacity: 15,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 330,
        noise_broadcast_distance: 100,
        ammo_type: "9x39mm",
        supported_components: [
            "枪管",
            "左导轨",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "弹匣座",
            "枪托"
        ],
        type: "射手步枪",
        weight: 4.39,
        size: 10
    },
    {
        name: "SVD狙击步枪",
        basic_damage: 56,
        benifit_shootrange: 70,
        recoil: 42,
        scope_open_speed: 48,
        holding_stability: 67,
        hipfire_accuracy: 34,
        armor_damage: 52,
        shoot_speed: 300,
        capacity: 10,
        fire_mode: "单发",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x54mm",
        supported_components: [
            "枪口",
            "枪管",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "弹匣",
            "弹匣座",
            "后握把"
        ],
        type: "射手步枪",
        weight: 4.73,
        size: 10
    },
    {
        name: "M14射手步枪",
        basic_damage: 40,
        benifit_shootrange: 40,
        recoil: 26,
        scope_open_speed: 58,
        holding_stability: 55,
        hipfire_accuracy: 48,
        armor_damage: 41,
        shoot_speed: 727,
        capacity: 10,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x51mm",
        supported_components: [
            "枪口",
            "枪管",
            "护木套件",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "弹匣座",
            "后握把",
        ],
        type: "射手步枪",
        weight: 4.2,
        size: 10
    },
    {
        name: "SKS射手步枪",
        basic_damage: 44,
        benifit_shootrange: 55,
        recoil: 30,
        scope_open_speed: 55,
        holding_stability: 60,
        hipfire_accuracy: 38,
        armor_damage: 42,
        shoot_speed: 510,
        capacity: 10,
        fire_mode: "单发",
        muzzle_base_speed: 575,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x39mm",
        supported_components: [
            "枪口",
            "枪管",
            "护木套件",
            "瞄准镜",
        ],
        type: "射手步枪",
        weight: 4.57,
        size: 10
    },
    {
        name: "SR-25射手步枪",
        basic_damage: 50,
        benifit_shootrange: 90,
        recoil: 56,
        scope_open_speed: 56,
        holding_stability: 59,
        hipfire_accuracy: 40,
        armor_damage: 55,
        shoot_speed: 364,
        capacity: 10,
        fire_mode: "单发",
        muzzle_base_speed: 550,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x51mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "上导轨",
            "左导轨",
            "右导轨",
            "上贴片",
            "左贴片",
            "右贴片",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托",
            "后握把",
        ],
        type: "射手步枪",
        weight: 4.88,
        size: 12
    },
    {
        name: "PSG-1射手步枪",
        basic_damage: 50,
        benifit_shootrange: 90,
        recoil: 60,
        scope_open_speed: 49,
        holding_stability: 66,
        hipfire_accuracy: 34,
        armor_damage: 55,
        shoot_speed: 300,
        capacity: 10,
        fire_mode: "单发",
        muzzle_base_speed: 750,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x51mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "战术设备",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "弹匣座",
            "枪托",
            "后握把",
            "扳机"
        ],
        type: "射手步枪",
        weight: 1.5,
        size: 10
    }
]