const pistol = [
    {
        name: "QSZ92G",
        basic_damage: 34,
        benifit_shootrange: 27,
        recoil: 55,
        scope_open_speed: 64,
        holding_stability: 41,
        hipfire_accuracy: 77,
        armor_damage: 32,
        shoot_speed: 375,
        capacity: 15,
        fire_mode: "单发",
        muzzle_base_speed: 400,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "下导轨",
            "瞄准镜"
        ],
        type: "手枪",
        weight: 2.10,
        size: 2
    },
    {
        name: ".35 左轮",
        basic_damage: 56,
        benifit_shootrange: 35,
        recoil: 34,
        scope_open_speed: 62,
        holding_stability: 43,
        hipfire_accuracy: 65,
        armor_damage: 39,
        shoot_speed: 182,
        capacity: 6,
        fire_mode: "单发",
        muzzle_base_speed: 340,
        noise_broadcast_distance: 300,
        ammo_type: ".357 马格南",
        supported_components: [
            "枪口",
            "枪管",
            "瞄准镜",
            "后握把"
        ],
        type: "手枪",
        weight: 2.18,
        size: 2
    },
    {
        name: "沙漠之鹰",
        basic_damage: 56,
        benifit_shootrange: 35,
        recoil: 40,
        scope_open_speed: 66,
        holding_stability: 39,
        hipfire_accuracy: 71,
        armor_damage: 34,
        shoot_speed: 207,
        capacity: 7,
        fire_mode: "单发",
        muzzle_base_speed: 340,
        noise_broadcast_distance: 300,
        ammo_type: ".50 AE",
        supported_components: [
            "枪口",
            "枪管",
            "瞄准镜",
            "后握把"
        ],
        type: "手枪",
        weight: 2.31,
        size: 2
    },
    {
        name: "G18",
        basic_damage: 22,
        benifit_shootrange: 10,
        recoil: 30,
        scope_open_speed: 62,
        holding_stability: 43,
        hipfire_accuracy: 67,
        armor_damage: 16,
        shoot_speed: 1172,
        capacity: 17,
        fire_mode: "全自动",
        muzzle_base_speed: 400,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "下导轨",
            "瞄准镜",
            "弹匣",
            "后握把"
        ],
        type: "手枪",
        weight: 1.89,
        size: 2
    },
    {
        name: "93R",
        basic_damage: 34,
        benifit_shootrange: 22,
        recoil: 44,
        scope_open_speed: 67,
        holding_stability: 38,
        hipfire_accuracy: 78,
        armor_damage: 32,
        shoot_speed: 672,
        capacity: 12,
        fire_mode: "连发",
        muzzle_base_speed: 400,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "下导轨",
            "瞄准镜",
            "弹匣",
            "后握把"
        ],
        type: "手枪",
        weight: 2.07,
        size: 2
    },
    {
        name: "G17",
        basic_damage: 27,
        benifit_shootrange: 27,
        recoil: 42,
        scope_open_speed: 70,
        holding_stability: 35,
        hipfire_accuracy: 75,
        armor_damage: 25,
        shoot_speed: 462,
        capacity: 17,
        fire_mode: "单发",
        muzzle_base_speed: 400,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "下导轨",
            "瞄准镜",
            "弹匣",
        ],
        type: "手枪",
        weight: 1.98,
        size: 2
    },
    {
        name: "M1911",
        basic_damage: 40,
        benifit_shootrange: 15,
        recoil: 39,
        scope_open_speed: 65,
        holding_stability: 40,
        hipfire_accuracy: 67,
        armor_damage: 30,
        shoot_speed: 373,
        capacity: 7,
        fire_mode: "单发",
        muzzle_base_speed: 400,
        noise_broadcast_distance: 300,
        ammo_type: ".45 ACP",
        supported_components: [
            "枪口",
            "枪管",
            "下导轨",
            "瞄准镜",
            "弹匣",
            "扳机",
            "后握把",
            "枪机"
        ],
        type: "手枪",
        weight: 1.00,
        size: 2
    }
]