const shotgun = [
    {
        name: "M1014霰弹枪",
        basic_damage: 14,
        benifit_shootrange: 12,
        recoil: 28,
        scope_open_speed: 53,
        holding_stability: 45,
        hipfire_accuracy: 52,
        armor_damage: 16,
        shoot_speed: 261,
        capacity: 7,
        fire_mode: "单发",
        muzzle_base_speed: 450,
        noise_broadcast_distance: 500,
        ammo_type: "12mm Gauge",
        supported_components: [
            "枪口",
            "枪管",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "枪托"
        ],
        type: "霰弹枪",
        weight: 3.62,
        size: 10
    },
    {
        name: "S12K霰弹枪",
        basic_damage: 13,
        benifit_shootrange: 10,
        recoil: 36,
        scope_open_speed: 49,
        holding_stability: 49,
        hipfire_accuracy: 48,
        armor_damage: 16,
        shoot_speed: 300,
        capacity: 5,
        fire_mode: "单发",
        muzzle_base_speed: 300,
        noise_broadcast_distance: 500,
        ammo_type: "12mm Gauge",
        supported_components: [
            "枪口",
            "枪管",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托",
            "枪托垫",
            "后握把"
        ],
        type: "霰弹枪",
        weight: 3.96,
        size: 10
    },
    {
        name: "M870霰弹枪",
        basic_damage: 14,
        benifit_shootrange: 12,
        recoil: 26,
        scope_open_speed: 57,
        holding_stability: 41,
        hipfire_accuracy: 49,
        armor_damage: 16,
        shoot_speed: 74,
        capacity: 6,
        fire_mode: "单发",
        muzzle_base_speed: 400,
        noise_broadcast_distance: 500,
        ammo_type: "12mm Gauge",
        supported_components: [
            "枪口",
            "枪管",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "枪托"
        ],
        type: "霰弹枪",
        weight: 3.41,
        size: 5
    }
]