const sniper = [
    {
        name: "SV-98狙击步枪",
        basic_damage: 55,
        benifit_shootrange: 150,
        recoil: 55,
        scope_open_speed: 44,
        holding_stability: 74,
        hipfire_accuracy: 26,
        armor_damage: 53,
        shoot_speed: 40,
        capacity: 7,
        fire_mode: "单发",
        muzzle_base_speed: 650,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x54mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "上导轨",
            "左导轨",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
        ],
        type: "狙击步枪",
        weight: 5.81,
        size: 6
    },
    {
        name: "R93狙击步枪",
        basic_damage: 55,
        benifit_shootrange: 150,
        recoil: 55,
        scope_open_speed: 52,
        holding_stability: 66,
        hipfire_accuracy: 28,
        armor_damage: 53,
        shoot_speed: 50,
        capacity: 10,
        fire_mode: "单发",
        muzzle_base_speed: 550,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x51mm",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "瞄准镜",
            "侧瞄具",
            "弹匣"
        ],
        type: "狙击步枪",
        weight: 5.22,
        size: 5
    },
    {
        name: "M700狙击步枪",
        basic_damage: 55,
        benifit_shootrange: 150,
        recoil: 24,
        scope_open_speed: 48,
        holding_stability: 70,
        hipfire_accuracy: 27,
        armor_damage: 53,
        shoot_speed: 48,
        capacity: 5,
        fire_mode: "单发",
        muzzle_base_speed: 650,
        noise_broadcast_distance: 600,
        ammo_type: "7.62x51mm",
        supported_components: [
            "枪口",
            "枪管",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "弹匣"
        ],
        type: "狙击步枪",
        weight: 5.11,
        size: 5
    },
    {
        name: "AWM狙击步枪",
        basic_damage: 100,
        benifit_shootrange: 200,
        recoil: 20,
        scope_open_speed: 44,
        holding_stability: 74,
        hipfire_accuracy: 23,
        armor_damage: 10,
        shoot_speed: 35,
        capacity: 5,
        fire_mode: "单发",
        muzzle_base_speed: 750,
        noise_broadcast_distance: 800,
        ammo_type: ".338 Lapua Mag AP   ",
        supported_components: [
            "枪口",
            "枪管",
            "脚架",
            "上导轨",
            "左导轨",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
        ],
        type: "狙击步枪",
        weight: 5.81,
        size: 6
    }
]