const submachine = [
    {
        name: "Vector冲锋枪",
        basic_damage: 32,
        benifit_shootrange: 20,
        recoil: 38,
        scope_open_speed: 69,
        holding_stability: 42,
        hipfire_accuracy: 52,
        armor_damage: 28,
        shoot_speed: 1091,
        capacity: 17,
        fire_mode: "全自动/单发/连发",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 300,
        ammo_type: ".45 ACP",
        supported_components: [
            "枪管",
            "枪口",       // 修正OCR"检口"
            "枪托",
            "弹匣",
            "弹匣座",
            "前握把",
            "瞄准镜",
            "上导轨",
            "侧瞄具"     // 修正OCR"初瞄具"
        ],
        type: "冲锋枪",
        weight: 2.9,
        size: 8
    },
    {
        name: "MP7冲锋枪",
        basic_damage: 32,
        benifit_shootrange: 20,
        recoil: 55,
        scope_open_speed: 67,
        holding_stability: 44,
        hipfire_accuracy: 68,
        armor_damage: 28,
        shoot_speed: 950,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 450,
        noise_broadcast_distance: 300,
        ammo_type: "4.6x30mm",
        supported_components: [
            "后握把",
            "枪管",
            "枪口",
            "枪托",
            "弹匣",
            "前握把",
            "瞄准镜",
            "左导轨",
            "右导轨",
            "侧瞄具"  // 修正OCR识别错误"侧目头"
        ],
        type: "冲锋枪",
        weight: 3.6,
        size: 8
    },
    {
        name: "P90冲锋枪",
        basic_damage: 32,
        benifit_shootrange: 20,
        recoil: 48,
        scope_open_speed: 56,
        holding_stability: 45,
        hipfire_accuracy: 60,
        armor_damage: 35,
        shoot_speed: 898,
        capacity: 50,
        fire_mode: "单发/全自动",
        muzzle_base_speed: 450,
        noise_broadcast_distance: 300,
        ammo_type: "5.7x28mm",
        supported_components: [
            "枪管",
            "枪口",
            "枪托",
            "前握把",
            "瞄准镜",
            "右导轨",
            "侧瞄具",
            "托腮板"
        ],
        type: "冲锋枪",
        weight: 2.87,
        size: 8
    },
    {
        name: "SR-3M紧凑突击步枪",
        basic_damage: 36,
        benifit_shootrange: 15,
        recoil: 45,
        scope_open_speed: 68,
        holding_stability: 43,
        hipfire_accuracy: 68,
        armor_damage: 48,
        shoot_speed: 747,
        capacity: 15,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 330,
        noise_broadcast_distance: 300,
        ammo_type: "9x39mm",
        supported_components: [
            "握把",
            "枪管",
            "枪口",
            "左导轨",
            "右导轨",
            "枪托",
            "弹匣",
            "弹匣座",
            "瞄准镜",
            "侧瞄具",
            "拉机柄"
        ],
        type: "冲锋枪",
        weight: 4.15,
        size: 8
    },
    {
        name: "MP5冲锋枪",
        basic_damage: 30,
        benifit_shootrange: 20,
        recoil: 53,
        scope_open_speed: 66,
        holding_stability: 45,
        hipfire_accuracy: 68,
        armor_damage: 32,
        shoot_speed: 820,
        capacity: 30,
        fire_mode: "全自动/单发/连发",
        muzzle_base_speed: 450,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托"
        ],
        type: "冲锋枪",
        weight: 2.7,
        size: 8
    },
    {
        name: "UZI冲锋枪",
        basic_damage: 28,
        benifit_shootrange: 20,
        recoil: 50,
        scope_open_speed: 68,
        holding_stability: 43,
        hipfire_accuracy: 66,
        armor_damage: 35,
        shoot_speed: 780,
        capacity: 25,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 450,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "左导轨",
            "右导轨",
            "护木",
            "瞄准镜",
            "前握把",
            "弹匣",
            "弹匣座",
            "枪托",
        ],
        type: "冲锋枪",
        weight: 2.2,
        size: 8
    },
    {
        name: "野牛冲锋枪",
        basic_damage: 32,
        benifit_shootrange: 20,
        recoil: 43,
        scope_open_speed: 62,
        holding_stability: 49,
        hipfire_accuracy: 63,
        armor_damage: 35,
        shoot_speed: 659,
        capacity: 32,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "左导轨",
            "右导轨",
            "护木",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托",
            "枪托垫",
            "后握把",
        ],
        type: "冲锋枪",
        weight: 2.1,
        size: 8
    },
    {
        name: "SMG-45冲锋枪",
        basic_damage: 35,
        benifit_shootrange: 27,
        recoil: 52,
        scope_open_speed: 70,
        holding_stability: 41,
        hipfire_accuracy: 65,
        armor_damage: 40,
        shoot_speed: 605,
        capacity: 25,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 300,
        ammo_type: ".45 ACP",
        supported_components: [
            "枪口",
            "枪管",
            "上导轨",
            "左导轨",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "弹匣座",
            "枪托",
            "后握把",
        ],
        type: "冲锋枪",
        weight: 3.0,
        size: 8
    },
    {
        name: "勇士冲锋枪",
        basic_damage: 36,
        benifit_shootrange: 20,
        recoil: 40,
        scope_open_speed: 63,
        holding_stability: 48,
        hipfire_accuracy: 67,
        armor_damage: 35,
        shoot_speed: 700,
        capacity: 30,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 500,
        noise_broadcast_distance: 300,
        ammo_type: "9x19mm",
        supported_components: [
            "枪口",
            "枪管",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "弹匣座",
            "枪托",
            "枪托垫",
            "后握把",
        ],
        type: "冲锋枪",
        weight: 3.44,
        size: 8
    },
    {
        name: "MP7冲锋枪",
        basic_damage: 29,
        benifit_shootrange: 20,
        recoil: 55,
        scope_open_speed: 67,
        holding_stability: 44,
        hipfire_accuracy: 68,
        armor_damage: 27,
        shoot_speed: 950,
        capacity: 20,
        fire_mode: "全自动/单发",
        muzzle_base_speed: 450,
        noise_broadcast_distance: 300,
        ammo_type: "4.6x30mm",
        supported_components: [
            "枪口",
            "枪管",
            "左导轨",
            "右导轨",
            "瞄准镜",
            "侧瞄具",
            "前握把",
            "弹匣",
            "枪托",
        ],
        type: "冲锋枪",
        weight: 3.6,
        size: 8
    }
]